### ISSUE TITLE
Lagging "Gallery"

### ISSUE THREAD

**Issue by Strg-Felix** [Musab-Hassan/musabhassan.com#23]
Sorry to bother you. Really really love your site. I added a gallery that opens in the work details "site". But unfortunately this makes the site very slow and lagging. Do you know of any way to fix this? Would really appreciate your help.

**Comment by Musab-Hassan** [comment]
Is the `musabhassan.com` scroller laggy or is your implementation of the work scroller laggy?

If its your implementation, you can try a few of the things that I used within the work component class that increase performance. 

The gallery scroller is broken into two parts both of which work independently from one another, the interactive scroller and the three.js effects. The three.js effects will lag on lower end hardware since they are 3d WebGL effects, I just ignored lag entirely by just disabling the three.js effects on lower end hardware using a library called detect-gpu. 

Here's the code snippet I used, its in the `sections/work.svelte` file.
```js
...
// Only enable ThreeJS warping effect if device can handle it
if (gpuTier.tier >= 2 && !gpuTier.isMobile && gpuTier.fps >= 30) new ImageRenderer(container, images);
...
```
you can also reduce your mesh geometry, lower geometry will make your effect less "warpy" but will increase performance. You can find the geometry definition in `effects/defaults/image-mesh.ts`.

```js
...
this.geometry = new THREE.PlaneBufferGeometry(1, 1, 4, 6);
...
```
I can help you out more if you share the specific part that's lagging, your hardware details, and what your doing to fix it.

**Comment by Strg-Felix** [comment]
Thx for your quick response. Really appreciate your help, very kind of you Musab. It´s my implementation of the gallery section that makes the whole thing laggy. My guess is that the reason for that is that the layout of the gallery is calculated "on the fly". I tried out different thinks like preloading but either my implemention for that was wrong or it seems to be useless.  Also I reduced the resolution of my images (now 1-3MB). I`m not a programmer myself so I got some issues with that kind of troubleshooting. Attached you can find my code for the work section. Feel free to correct me for my  coding haha 
[work.txt](https://github.com/Musab-Hassan/musabhassan.com/files/11661133/work.txt)

**Comment by Musab-Hassan** [comment]
You don't seem to have modified much here, it looks fine. Try compressing your images and modifying the geometry. Other than that, I cant really help much if you cant troubleshoot it further.
